[package]
name = "capabilityapi"
version = "0.1.0"
edition = "2021"
authors = ["Kenneth Fossen <kenneth.fossen@uib.no>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "3.0.0-beta.9"
actix-web = "4.0.0-beta.8"
anyhow = "1.0.43"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
sqlite = "0.26.0"
tokio = { version = "1.11.0", features = ["full"] }