[package]
name = "capabilityapi"
version = "0.1.0"
edition = "2021"
authors = ["Kenneth Fossen <kenneth.fossen@uib.no>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-http = "3.0.0-beta.9"
actix-web = "4.0.0-beta.8"
anyhow = "1.0.43"
async-trait = "0.1.51"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.67"
sqlx = { version = "0.5.7", features = ["migrate","runtime-actix-rustls","sqlite","offline","macros"]}
tokio = { version = "1.11.0", features = ["full"] }